image: alpine:latest

pages:
  stage: deploy
  tags:
    - cdso-large
  script:
    - mkdir -p .public
    - cp -r * .public/ || true
    - mv .public public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH



